version: "3.0"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: on-failure