package org.example;// Generated by Selenium IDE

import static org.assertj.core.api.Assertions.assertThat;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

@ExtendWith(SeleniumJupiter.class)
public class AppTest {
    private WebDriver driver = new FirefoxDriver();
    // JavascriptExecutor js = (JavascriptExecutor) driver;


    @Test
    public void test0() {
        // Test name: test0
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("https://blazedemo.com/");
        // 2 | setWindowSize | 1920x1001 |
        driver.manage().window().setSize(new Dimension(1920, 1001));
        // 3 | click | name=fromPort |
        driver.findElement(By.name("fromPort")).click();
        // 4 | select | name=fromPort | label=Mexico City
        {
            WebElement dropdown = driver.findElement(By.name("fromPort"));
            dropdown.findElement(By.xpath("//option[. = 'Mexico City']")).click();
        }
        // 5 | click | css=.form-inline:nth-child(1) > option:nth-child(6) |
        driver.findElement(By.cssSelector(".form-inline:nth-child(1) > option:nth-child(6)")).click();
        // 6 | click | name=toPort |
        driver.findElement(By.name("toPort")).click();
        // 7 | select | name=toPort | label=London
        {
            WebElement dropdown = driver.findElement(By.name("toPort"));
            dropdown.findElement(By.xpath("//option[. = 'London']")).click();
        }
        // 8 | click | css=.form-inline:nth-child(4) > option:nth-child(3) |
        driver.findElement(By.cssSelector(".form-inline:nth-child(4) > option:nth-child(3)")).click();
        // 9 | click | css=.btn-primary |
        driver.findElement(By.cssSelector(".btn-primary")).click();
        // 10 | click | css=tr:nth-child(3) .btn |
        driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
        // 11 | click | id=inputName |
        driver.findElement(By.id("inputName")).click();
        // 12 | type | id=inputName | Tiago
        driver.findElement(By.id("inputName")).sendKeys("Tiago");
        // 13 | click | id=inputName |
        driver.findElement(By.id("inputName")).click();
        // 14 | type | id=inputName | Tiago Sora
        driver.findElement(By.id("inputName")).sendKeys("Tiago Sora");
        // 15 | click | id=address |
        driver.findElement(By.id("address")).click();
        // 16 | type | id=address | R. Das Tias
        driver.findElement(By.id("address")).sendKeys("R. Das Tias");
        // 17 | type | id=city | Penalva
        driver.findElement(By.id("city")).sendKeys("Penalva");
        // 18 | type | id=state | Viseu
        driver.findElement(By.id("state")).sendKeys("Viseu");
        // 19 | type | id=zipCode | 3554
        driver.findElement(By.id("zipCode")).sendKeys("3554");
        // 20 | click | id=zipCode |
        driver.findElement(By.id("zipCode")).click();
        // 21 | type | id=zipCode | 3554-159
        driver.findElement(By.id("zipCode")).sendKeys("3554-159");
        // 22 | click | css=.control-group:nth-child(7) |
        driver.findElement(By.cssSelector(".control-group:nth-child(7)")).click();
        // 23 | click | id=cardType |
        driver.findElement(By.id("cardType")).click();
        // 24 | click | css=option:nth-child(1) |
        driver.findElement(By.cssSelector("option:nth-child(1)")).click();
        // 25 | click | css=.control-group:nth-child(8) > .controls |
        driver.findElement(By.cssSelector(".control-group:nth-child(8) > .controls")).click();
        // 26 | click | id=creditCardNumber |
        driver.findElement(By.id("creditCardNumber")).click();
        // 27 | type | id=creditCardNumber | 26584582651
        driver.findElement(By.id("creditCardNumber")).sendKeys("26584582651");
        // 28 | click | id=creditCardMonth |
        driver.findElement(By.id("creditCardMonth")).click();
        // 29 | click | id=creditCardYear |
        driver.findElement(By.id("creditCardYear")).click();
        // 30 | type | id=creditCardYear | 2020
        driver.findElement(By.id("creditCardYear")).sendKeys("2020");
        // 31 | click | id=nameOnCard |
        driver.findElement(By.id("nameOnCard")).click();
        // 32 | type | id=nameOnCard | Tiago Sora
        driver.findElement(By.id("nameOnCard")).sendKeys("Tiago Sora");
        // 33 | click | css=.btn-primary |
        driver.findElement(By.cssSelector(".btn-primary")).click();
        // 34 | assertTitle | BlazeDemo Confirmation |
        assertThat(driver.getTitle().equals("BlazeDemo Confirmation"));

        driver.quit();
    }
}
