// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
public class WebTest {

  private WebDriver driver;
  JavascriptExecutor js;
  
  @Test
  public void testdrive() throws InterruptedException {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    // Test name: testdrive
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:3000/");
    // 2 | setWindowSize | 1920x1001 | 
    driver.manage().window().setSize(new Dimension(1920, 1001));
    Thread.sleep(6000);
    // 3 | mouseDown | id=select-1 | 
    {
      WebElement element = driver.findElement(By.id("select-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 4 | mouseUp | id=db1-California | 
    {
      WebElement element = driver.findElement(By.id("db1-California"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 5 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 6 | click | id=db1-France | 
    driver.findElement(By.id("db1-France")).click();
    Thread.sleep(6000);
    // 7 | mouseDown | id=select-2 | 
    {
      WebElement element = driver.findElement(By.id("select-2"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 8 | mouseUp | id=db2-Roubaix Serres, Nord-Pas-de-Calais, France | 
    {
      WebElement element = driver.findElement(By.id("db2-Roubaix Serres, Nord-Pas-de-Calais, France"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 9 | click | css=body | 
    driver.findElement(By.cssSelector("body")).click();
    // 10 | click | id=db2-Paris | 
    driver.findElement(By.id("db2-Paris")).click();
    // 11 | mouseOver | id=button1 | 
    {
      WebElement element = driver.findElement(By.id("button1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | id=button1 | 
    driver.findElement(By.id("button1")).click();
    Thread.sleep(6000);
    // 13 | mouseOut | id=button1 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.quit();
  }
}